# Generated by Django 4.1.7 on 2023-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formupload',
            name='image',
            field=models.FileField(upload_to='files'),
        ),
    ]
