# Generated by Django 4.1.7 on 2023-04-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_alter_formupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formupload',
            name='image',
            field=models.FileField(upload_to='Media/'),
        ),
    ]
