# Generated by Django 4.1.7 on 2023-04-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_remove_contactform_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactForm',
        ),
    ]
