# Generated by Django 4.1.7 on 2023-04-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='avatar',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
