# Generated by Django 4.1.7 on 2023-04-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0006_alter_contactform_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='avatar',
        ),
    ]
