# Generated by Django 4.1.7 on 2023-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Landsliderisk', models.CharField(max_length=30)),
                ('Debrisflowrisk', models.CharField(max_length=30)),
                ('Flashfloodrisk', models.CharField(max_length=30)),
            ],
        ),
    ]
