# Generated by Django 4.1.7 on 2023-05-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Temperature', models.CharField(max_length=30)),
                ('Digitalsignal', models.CharField(max_length=30)),
                ('Highestvalue', models.CharField(max_length=30)),
                ('Oscillatingpeak', models.CharField(max_length=30)),
            ],
        ),
    ]
