# Generated by Django 4.1.7 on 2023-04-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_sites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
