# Generated by Django 4.1.7 on 2023-04-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_delete_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=50)),
                ('Distric', models.CharField(max_length=50)),
                ('Commune', models.CharField(max_length=50)),
                ('Risk3h', models.CharField(max_length=50)),
                ('Risk12h', models.CharField(max_length=50)),
                ('Risk24h', models.CharField(max_length=50)),
                ('Risk48h', models.CharField(max_length=50)),
            ],
        ),
    ]
