# Generated by Django 4.1.7 on 2023-04-05 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('nameT', models.CharField(max_length=100)),
                ('nameH', models.CharField(max_length=100)),
                ('nameX', models.CharField(max_length=100)),
                ('nameMax', models.CharField(max_length=100)),
                ('nameMin', models.CharField(max_length=100)),
                ('nameTB', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
            ],
        ),
    ]
